# Generated by Django 4.2.5 on 2023-09-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intSocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
