# Generated by Django 4.2.5 on 2023-10-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intSocial', '0004_alter_comentario_user_alter_grupos_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
