# Generated by Django 4.2.5 on 2023-10-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intSocial', '0006_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='url',
        ),
    ]
