# Generated by Django 4.2.5 on 2023-11-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intSocial', '0008_alter_profile_bio_alter_profile_email_publico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='imagen_header',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
