# Generated by Django 4.2.5 on 2023-12-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intSocial', '0010_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
